apiVersion: v1
kind: Secret
metadata:
  name: backend-db-secret
  namespace: framely-stage
type: Opaque
stringData:
  connection-string: >
    Server=sql-server,1433;
    Database=FramelyDb;
    User Id=sa;
    Password=StrongPassword@123;
    TrustServerCertificate=True;
    Encrypt=False;
