apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: framely-stage-ingress
  namespace: framely-stage
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: localhost
      http:
        paths:
          # ------------------------------------------------------------
          # Backend API
          # ------------------------------------------------------------
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80

          # ------------------------------------------------------------
          # Admin Frontend
          # ------------------------------------------------------------
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: frontend-admin
                port:
                  number: 80

          # ------------------------------------------------------------
          # Customer Frontend
          # ------------------------------------------------------------
          - path: /app
            pathType: Prefix
            backend:
              service:
                name: frontend-customer
                port:
                  number: 80
