apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: framely-stage-ingress
  namespace: framely-stage
  annotations:
    kubernetes.io/ingress.class: nginx

    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"

    # TLS-ready (enable later)
    # cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    # ---------------- Backend API ----------------
    - host: framely-api-sg.rohitsharma.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80

    # ------------- Frontend Customer -------------
    - host: framely-sg.rohitsharma.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-customer
                port:
                  number: 80

    # --------------- Frontend Admin ---------------
    - host: framely-admin-sg.rohitsharma.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-admin
                port:
                  number: 80
