# ======================================================================
# images.yaml
# Framely â€“ Mega DevOps AKS Project
#
# Purpose:
# - Define Docker image names for each application
# - Keep image naming consistent across environments
# - Decouple image naming from build logic
#
# Image Naming Convention (Docker Hub):
#   <dockerhub-username>/<application-name>
#
# Example:
#   mrsharma151/backend:abc123
# ======================================================================

images:
  backend: mrsharma151/backend
  frontend-admin: mrsharma151/frontend-admin
  frontend-customer: mrsharma151/frontend-customer
