# ======================================================================
# registries.yaml
# Framely â€“ Mega DevOps AKS Project
#
# Purpose:
# - Define container registry details per environment
# - Keep registry configuration completely out of pipelines
# - Support seamless migration between registries
#
# DESIGN PRINCIPLES:
# - Pipelines never hardcode registry URLs
# - Authentication strategy depends on registry type
# - Azure ACR uses Managed Identity (no credentialsId)
# ======================================================================

registries:
  # --------------------------------------------------------------------
  # STAGE Environment Registry
  # --------------------------------------------------------------------
  stage:
    type: acr
    registryUrl: acrframelystage.azurecr.io
    auth:
      type: managed-identity


  # --------------------------------------------------------------------
  # PROD Environment Registry
  # --------------------------------------------------------------------
  prod:
    type: acr
    registryUrl: acrframelystage.azurecr.io
    auth:
      type: managed-identity
