# ======================================================================
# registries.yaml
# Framely â€“ Mega DevOps AKS Project
#
# Purpose:
# - Define container registry details per environment
# - Keep registry configuration out of pipelines
# - Allow environment-specific isolation
#
# NOTE:
# - Credentials are stored in Jenkins Credentials Manager
# - Pipelines only reference credential IDs
# ======================================================================

registries:
  stage:
    type: dockerhub
    registryUrl: docker.io
    repositoryPrefix: mrsharma151
    credentialsId: dockerhub-creds

  prod:
    type: acr
    registryUrl: framelyacr.azurecr.io
    repositoryPrefix: framely
    credentialsId: acr-prod-creds
