apiVersion: v1
kind: Service
metadata:
  name: frontend-admin
  namespace: framely-stage
  labels:
    app: frontend-admin
spec:
  type: ClusterIP
  selector:
    app: frontend-admin
  ports:
    - name: http
      port: 80
      targetPort: 3000
